### ISSUE TITLE
翻译 rust-std 的 time 模块

### ISSUE THREAD

**Issue by plus7wist** [kriry/kriry-dev#1]
我来做这事儿，PR 正在路上。

**Comment by plus7wist** [comment]
#2

**Comment by plus7wist** [comment]
这个翻译过程体验不是很好，HTML 读写都挺费事，而且不同页面有很多重复的地方，需要拷贝来拷贝去的。

Rust 标准库的文档好似是从代码注释里编译出来的，标准库文档也在 src 链接了实现页，所以是不是可以考虑直接翻译代码的文档注释，然后编译成中文的？

这样读写困难、翻译重复还有实现链接没有翻译的问题就一并解决了。

<https://github.com/rust-lang/rust#building-documentation>

> If you’d like to build the documentation, it’s almost the same:
> ```
> $ ./x.py doc
> ```

**Comment by krircc** [comment]
你的意思是源码拷贝过来搞，这样别人贡献太难吧😄，翻译文档一遍就够了

**Comment by krircc** [comment]
原生类型，宏，标准库源码也不在一个地方

**Comment by plus7wist** [comment]
我持保留态度，这样可能合并的时候不会太方便。不过我可以试一下。

**Comment by plus7wist** [comment]
说起来，这个 rust-std 是哪里下的？还是也是编译出来的？

**Comment by krircc** [comment]
@plus7wist 已经弄好了,现在可以直接翻译源码文档，进行中文化了

https://github.com/kriry/rust

**Comment by plus7wist** [comment]
krirr/rust 的 master 代码好像是同步了 rust-lang 的 master 分支，但是 https://dev.kriry.com/www/rust-std/std/ 上标识的是 release 1.38.0 的文档。这是有什么考虑吗？

我们确实应该翻译一个发布版本的文档对吗？

**Comment by plus7wist** [comment]
我 diff 了一下 std/libstd 在 master 和 1.38.0 的区别，从文档注释到代码差别都挺大的。

如果要试一试 1.38.0，那我可以分享一下经验。`./x.py doc` 是能用的，但是要检出自模块，还要编译 llvm 的生产代码，第一次过程可能要几个小时（看网速）。修改 src/libstd/ 中某个文件的代码注释之后，`./x.py doc` 会触发对很多东西的重新编译，耗时也很长，可能有几分钟。

这个体验还得优化优化，才能让更多志愿者翻译过程变得方便一点。

**Comment by krircc** [comment]
@plus7wist 是的，我就是考虑翻译HTML这个问题，下次升级，需要改动的太多，而且不易追踪.
直接Fork官方Repo,每月发布新版时，同步一下同时可以追踪那些变化需要翻译，而且很多版本细节不需要手动去做.kriry-dev的Rust标准库文档是kriry/rust直接生成的，我们只需要翻译kriry/rust的源码文档就行了，这里以后就不需要动了

**Comment by krircc** [comment]
kriry-dev的文档，在我们翻译kriry/rust源码文档同步后，直接替换掉，kriry/rust目前相当于重新翻译，好在刚翻译的不多

**Comment by krircc** [comment]
是的我也编译过一次，烧机子。现在应该可以直接fork本仓库进入libstd 直接cargo doc，很方便容易.
目前同步的是官方master版本

**Comment by krircc** [comment]
现在应该可以直接fork本仓库进入libstd 直接cargo doc
https://github.com/kriry/rust#%E5%AE%9E%E6%96%BD
这个简单步骤，在你那里好使吗？

**Comment by plus7wist** [comment]
这个步骤是 OK 的。

但我的问题是 kriry/rust 的 master 跟 1.38.0 差别很大呀？为什么要用这个分支呢？我们的目的就是翻译 rust-lang/master 而不是翻译发布版本的 rust 标准库吗？我不太能理解这个做法……还是说你的意思是等 1.41 发布，我们放弃 1.40 之前的版本？

**Comment by krircc** [comment]
kriry-dev的是 1.38.0 stable文档，在我们翻译kriry/rust源码文档同步后，直接替换掉，kriry/rust目前相当于重新翻译，好在kriry-dev刚翻译的不多.
我的想法是翻译mster文档. 你是怎么想的?

**Comment by plus7wist** [comment]
我觉得我们先明确一下背景和目的。

rust-lang/rust 每天都会从 master 构建一个 nightly 版本，这个版本有很多特性，但是距离稳定还很远。六周之后，nightly 会进入 beta，beta 六周之后，会进入 stable，发布一个 rust 工具链的版本。现在的 stable 频道版本是 1.38.0，它对应的节点被打了 1.38.0 的 tag。现在的 nightly 是 1.40.0-nightly (2477e2493 2019-11-04)，也就是昨天发布的版本。

也就是说，从 nightly 开始，到 stable 有十二周，不到三个月。但是相邻两个 stable 版本之间只有六周，大概一个半月。

所以我推测你说的「每月发新版本」是指 stable 版本。但是从 master 出发，合并 stable 版本，在 1.41 稳定之前，都得不到稳定版本。从 stable 出发合并 stable 版本才能得到 1.38、1.39 和 1.40 的稳定版本，所以我问你是不是打算放弃 1.41 之前的版本。

**Comment by krircc** [comment]
其实你知道Stable版本内容在一个版本周期内是不变的，我们只需要在每月发布新版本时与官方同步就好了。也就是说mster虽然每天更新，但是已经Stable的内容几乎不会变化，除非发布2.0 😅
我们只需要翻译master中Stable的文档，其实源码都有标签属性，实在怕错，可以打开官方标准库文档api, 翻译之后检查一下效😀，你说呢？
这样做需要操作步骤最少，甚至可以直接web端对照翻译，业余几分钟都可以贡😂

**Comment by krircc** [comment]
@plus7wist 虽然你对比的数据没错，我看了一下，libstd大概140个文件， libcore大概100个。真的不多, 标注库每个版本变化通常只有几个api, 你看fs文件对比
[1.38](https://github.com/kriry/rust/blob/1.38.0/src/libstd/fs.rs) - 
[master](https://github.com/kriry/rust/blob/master/src/libstd/fs.rs) 只是增加了几十行注释文档，这个还是比较多的, 有的文件几个版本都不会动

**Comment by plus7wist** [comment]
此诚良言，心悦诚服。
